"""agregar indice unico a nombre_departamento

Revision ID: 086db39fcb1b
Revises: dc2226599f96
Create Date: 2026-07-15 12:07:09.615658

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '086db39fcb1b'
down_revision: Union[str, None] = 'dc2226599f96'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('departamentos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_departamentos_nombre_departamento'), ['nombre_departamento'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('departamentos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_departamentos_nombre_departamento'))

    # ### end Alembic commands ###
