"""crear tablas nuevas

Revision ID: 48f3f16ec316
Revises: e0b801f668bf
Create Date: 2026-07-07 18:28:25.083178

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '48f3f16ec316'
down_revision: Union[str, None] = 'e0b801f668bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clientes',
    sa.Column('id_cliente', sa.Integer(), nullable=False),
    sa.Column('nombre_cliente', sa.String(length=45), nullable=False),
    sa.PrimaryKeyConstraint('id_cliente')
    )
    op.create_table('trabajadores',
    sa.Column('id_trabajador', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=45), nullable=False),
    sa.Column('puesto', sa.String(length=45), nullable=False),
    sa.PrimaryKeyConstraint('id_trabajador')
    )
    op.create_table('ventas',
    sa.Column('id_venta', sa.Integer(), nullable=False),
    sa.Column('id_cliente', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_cliente'], ['clientes.id_cliente'], ),
    sa.PrimaryKeyConstraint('id_venta')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ventas')
    op.drop_table('trabajadores')
    op.drop_table('clientes')
    # ### end Alembic commands ###
