"""agregar dni a clientes

Revision ID: 77accdf32ec1
Revises: 8097bfe59908
Create Date: 2026-07-08 18:55:33.642071

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '77accdf32ec1'
down_revision: Union[str, None] = '8097bfe59908'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # 1. Agregar la columna como opcional primero
    op.add_column('clientes', sa.Column('dni_cliente', sa.String(length=12), nullable=True))

    # 2. Rellenar los valores para las filas que ya existen
    op.execute("UPDATE clientes SET dni_cliente = '12345678A' WHERE nombre_cliente = 'Juan Pérez'")
    op.execute("UPDATE clientes SET dni_cliente = '87654321B' WHERE nombre_cliente = 'María López'")
    op.execute("UPDATE clientes SET dni_cliente = '11223344C' WHERE nombre_cliente = 'Carlos Sánchez'")
    op.execute("UPDATE clientes SET dni_cliente = '55667788D' WHERE nombre_cliente = 'Ana Torres'")
    op.execute("UPDATE clientes SET dni_cliente = '99887766E' WHERE nombre_cliente = 'Luis Ramírez'")
    op.execute("UPDATE clientes SET dni_cliente = '44556677F' WHERE nombre_cliente = 'Sofía Gómez'")
    op.execute("UPDATE clientes SET dni_cliente = '22334455G' WHERE nombre_cliente = 'Pedro Castillo'")
    op.execute("UPDATE clientes SET dni_cliente = '66778899H' WHERE nombre_cliente = 'Laura Fernández'")

    # 3. Ahora sí, volverla obligatoria
    op.alter_column('clientes', 'dni_cliente', nullable=False)

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clientes', 'dni_cliente')
    # ### end Alembic commands ###
