"""crear tabla departamentos

Revision ID: 7edc9946ec1d
Revises: eee2a84596d3
Create Date: 2026-07-13 15:33:40.969195

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7edc9946ec1d'
down_revision: Union[str, None] = 'eee2a84596d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('departamentos',
    sa.Column('id_departamento', sa.Integer(), nullable=False),
    sa.Column('nombre_departamento', sa.String(length=50), nullable=False),
    sa.Column('descripcion', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id_departamento')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('departamentos')
    # ### end Alembic commands ###
