"""agregar email a trabajadores

Revision ID: 8097bfe59908
Revises: 48f3f16ec316
Create Date: 2026-07-08 18:18:34.080236

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8097bfe59908'
down_revision: Union[str, None] = '48f3f16ec316'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # 1. Agregar la columna como opcional primero
    op.add_column('trabajadores', sa.Column('email', sa.String(length=45), nullable=True))

    # 2. Rellenar los valores para las filas que ya existen
    op.execute("UPDATE trabajadores SET email = 'robert10@gmail.com' WHERE nombre = 'Roberto Díaz'")
    op.execute("UPDATE trabajadores SET email = 'elena10@gmail.com' WHERE nombre = 'Elena Martínez'")
    op.execute("UPDATE trabajadores SET email = 'miguel@gmail.com' WHERE nombre = 'Miguel Herrera'")
    op.execute("UPDATE trabajadores SET email = 'patricia@gmail.com' WHERE nombre = 'Patricia Rivas'")

    # 3. Ahora sí, volverla obligatoria
    op.alter_column('trabajadores', 'email', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trabajadores', 'email')
    # ### end Alembic commands ###
