"""agregar tabla proveedores

Revision ID: b2a6059b3066
Revises: 473ff287d787
Create Date: 2026-07-14 15:51:11.984370

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b2a6059b3066'
down_revision: Union[str, None] = '473ff287d787'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('proveedores',
    sa.Column('id_proveedor', sa.Integer(), nullable=False),
    sa.Column('nombre_proveedor', sa.String(length=150), nullable=False),
    sa.Column('contacto_email', sa.String(length=150), nullable=True),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id_proveedor')
    )
    with op.batch_alter_table('proveedores', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_proveedores_nombre_proveedor'), ['nombre_proveedor'], unique=True)

    with op.batch_alter_table('departamentos', schema=None) as batch_op:
        batch_op.drop_index('idx_departamento_nombre')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('departamentos', schema=None) as batch_op:
        batch_op.create_index('idx_departamento_nombre', ['nombre_departamento'], unique=False)

    with op.batch_alter_table('proveedores', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_proveedores_nombre_proveedor'))

    op.drop_table('proveedores')
    # ### end Alembic commands ###
